const { contextBridge, ipcRenderer } = require('electron');

contextBridge.exposeInMainWorld('api', {
  getAppMeta: () => ipcRenderer.invoke('get-app-meta'),
  getUpdateStatus: () => ipcRenderer.invoke('get-update-status'),
  checkForUpdates: () => ipcRenderer.invoke('check-for-updates'),
  installDownloadedUpdate: () => ipcRenderer.invoke('install-downloaded-update'),
  getState: () => ipcRenderer.invoke('get-state'),
  clearVideos: () => ipcRenderer.invoke('clear-videos'),
  addVideoByDriveLink: (payload) => ipcRenderer.invoke('add-video-by-drive-link', payload),
  importDriveFolder: (payload) => ipcRenderer.invoke('import-drive-folder', payload),
  refreshDriveFolder: (payload) => ipcRenderer.invoke('refresh-drive-folder', payload),
  fetchDriveVideos: (payload) => ipcRenderer.invoke('fetch-drive-videos', payload),
  setDriveFolderLink: (payload) => ipcRenderer.invoke('set-drive-folder-link', payload),
  uploadVideosToDrive: (payload) => ipcRenderer.invoke('upload-videos-to-drive', payload),
  deleteDriveVideo: (payload) => ipcRenderer.invoke('delete-drive-video', payload),
  deleteAllDriveVideos: (payload) => ipcRenderer.invoke('delete-all-drive-videos', payload),
  openExternal: (url) => ipcRenderer.invoke('open-external', url),
  autoAssignVideoTitles: (titles) => ipcRenderer.invoke('auto-assign-video-titles', titles),
  applyGlobalMetadataToVideos: () => ipcRenderer.invoke('apply-global-metadata-to-videos'),
  selectOAuthJson: () => ipcRenderer.invoke('select-oauth-json'),
  addChannel: (payload) => ipcRenderer.invoke('add-channel', payload),
  getChannelToken: (channelId) => ipcRenderer.invoke('get-channel-token', channelId),
  deleteChannel: (channelId) => ipcRenderer.invoke('delete-channel', channelId),
  setChannelSelected: (payload) => ipcRenderer.invoke('set-channel-selected', payload),
  starChannel: (channelId) => ipcRenderer.invoke('star-channel', channelId),
  openChannel: (channelId) => ipcRenderer.invoke('open-channel', channelId),
  updateSettings: (payload) => ipcRenderer.invoke('update-settings', payload),
  startUpload: () => ipcRenderer.invoke('start-upload'),
  stopUpload: () => ipcRenderer.invoke('stop-upload'),
  startAutomation: () => ipcRenderer.invoke('start-automation'),
  stopAutomation: () => ipcRenderer.invoke('stop-automation'),
  setVideosPerDay: (value) => ipcRenderer.invoke('set-videos-per-day', value),
  getAutomationStatus: () => ipcRenderer.invoke('get-automation-status'),
  getAutomationUpgradeStatus: () => ipcRenderer.invoke('get-automation-upgrade-status'),
  preflightAutomation: () => ipcRenderer.invoke('preflight-automation'),
  checkInternet: () => ipcRenderer.invoke('check-internet'),
  onLog: (callback) => ipcRenderer.on('log', (event, message) => callback(message)),
  onProgress: (callback) => ipcRenderer.on('progress', (event, payload) => callback(payload)),
  onDriveSyncProgress: (callback) => ipcRenderer.on('drive-sync-progress', (event, payload) => callback(payload)),
  onDriveUploadItem: (callback) => ipcRenderer.on('drive-upload-item', (event, payload) => callback(payload)),
  onState: (callback) => ipcRenderer.on('state', (event, payload) => callback(payload)),
  onUpdateStatus: (callback) => ipcRenderer.on('update-status', (event, payload) => callback(payload)),
});
